### ISSUE TITLE
Issue with safari browser extension login; email support not available

### ISSUE THREAD

**Issue by jamesware** [bufferapp/buffer-safari#9]
I saw a previous similar issue raised (#4) and marked as closed, though very recent comment threads suggest this is an ongoing problem.

A-Farmer has provided some comments: I tried changing the overlay/new tab settings, and this has not resolved it for me.  Further advice was to email hello@buffer.com.

I emailed hello@buffer.com, but received an auto-reply saying that email support is now limited to paying customers, and I am still evaluating on the free version.  The email pointed to FAQs, but I can't find anything there.

I'm not sure how else to connect for advice.

**Comment by A-Farmer** [comment]
Hey there, @jamesware! The issue with the Safari Browser and the Extension will be related to how Safari handles cookies in a 3rd Party context and the cross-site tracking. As long as the Browser is adjusted, logging in within Safari will be possible.

To adjust this, go ahead and ensure the Privacy settings of Safari are set as they appear within this screenshot: http://hi.buffer.com/903040f6d266. If adjustments are made, be sure to restart Safari entirely.

**Comment by notasausage** [comment]
This is not a proper solution to the issue. Why should anyone have to reduce or eliminate their browser history just to login to a single web service? Also, this wasn't an issue up until recently, so it sounds to me like something Buffer changed on their end caused the issue in the first place.

Please reopen this and address it with a proper fix on your end rather than ask end users to change their privacy settings.

**Comment by notasausage** [comment]
I should also mention that logging into Buffer via email + password in the Pocket Mac app is still broken as well.
